### ISSUE TITLE
Socket Hangup

### ISSUE THREAD

**Issue by devinellis** [DudaDev/partner-api#103]
I know this is very likely not an issue with this library, but I thought it might help if I notify you here so you can forward the issue to whoever is responsible for the sandbox-api. I seem to get intermittent socket hangups that are slowing down the QA process, because to the tester it looks like my app is having trouble. Here's a log of one. I got two of these errors in a row, and the third time the app install request worked:

```
2023-04-26T18:14:42.431265692Z [error] d7715e5f-dd89-406c-b865-4f390e084e6f request error: message=ECONNRESET
2023-04-26T18:14:42.432450639Z Error
2023-04-26T18:14:42.432495407Z     at _log (/var/www/node_modules/@dudadev/partner-api/dist/lib/log.js:25:21)
2023-04-26T18:14:42.432500376Z     at Function.error (/var/www/node_modules/@dudadev/partner-api/dist/lib/log.js:31:25)
2023-04-26T18:14:42.432504127Z     at ClientRequest.<anonymous> (/var/www/node_modules/@dudadev/partner-api/dist/lib/http.js:139:24)
2023-04-26T18:14:42.432508189Z     at ClientRequest.emit (node:events:513:28)
2023-04-26T18:14:42.432511712Z     at TLSSocket.socketOnEnd (node:_http_client:518:9)
2023-04-26T18:14:42.432515420Z     at TLSSocket.emit (node:events:525:35)
2023-04-26T18:14:42.432518917Z     at endReadableNT (node:internal/streams/readable:1359:12)
2023-04-26T18:14:42.432522445Z     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
```json
{
  "level": 50,
  "time": 1682532882431,
  "pid": 19,
  "hostname": "652ceabca7d9",
  "code": "ECONNRESET",
  "body": {
    "auth": {
      "type": "bearer",
      "authorization_code": "zqnk...",
      "refresh_token": "fhGI...",
      "expiration_date": 1682576082012
    },
    "api_endpoint": "https://api-sandbox.duda.co",
    "installer_account_uuid": "0ea1...afc",
    "account_owner_uuid": "0ea1...afc",
    "user_lang": null,
    "app_plan_uuid": "8473...223",
    "recurrency": null,
    "source": "UI",
    "site_name": "3896...dcc",
    "free": true
  },
  "stack": "Error: socket hang up\n    at connResetException (node:internal/errors:711:14)\n    at TLSSocket.socketOnEnd (node:_http_client:518:23)\n    at TLSSocket.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
  "type": "Error",
  "msg": "socket hang up"
}
```

For now, I'm just going to add some retry logic. (BTW, this is somewhat related to my previous issue https://github.com/DudaDev/partner-api/issues/82)

**Comment by jhummel** [comment]
@devinellis sorry for the slow response here. Just checking here - did the fix for issue #82 at least make sure that the library was correctly throwing network errors? Are you still having that issue as well? Or just the hangups? I'm not sure if you saw, but there are automatic retries built into the library as well:

```
const duda = new Duda({
  ...,
  maxNetworkRetries: 2,
  timeout: 1000
});
```
